Apply list of rangeKeys with associated indices
screwdriver-cd/dynamic-dynamodb pull request #14
Opened 2016-09-15 21:10 UTC by FenrirUnbound

This PR maps a list of `rangeKey` with the index that it aligns with. Defining a `rangeKey` will allow us to use an *order* operation when performing a DynamoDB query.

2016-09-15 21:21 UTC, petey commented on index.js
> +        if (schema.rangeKeys) {
You may want `Array.isArray(schema.rangeKeys)`

2016-09-15 21:22 UTC, petey requested changes

2016-09-15 22:11 UTC, FenrirUnbound commented on index.js
> +        if (schema.rangeKeys) {
Added a test case to address that 👍

2016-09-15 22:13 UTC, stjohnjohnson approved these changes
Seems magical :( ![](https://media1.giphy.com/media/tGZRCBAPhCXxm/200w.gif)

2016-09-15 22:15 UTC, d2lam approved these changes

2016-09-16 18:28 UTC, petey approved these changes

2016-09-16 18:29 UTC, petey commented
👍  
![200w](https://cloud.githubusercontent.com/assets/78533/18597033/dda60666-7c00-11e6-86aa-1e75c281e03f.gif)

2016-09-16 18:29 UTC, merged